# docker-compose.yml
# version: '3.8' # Remove obsolete version tag

services:
  web:
    build: . # Build from Dockerfile again
    image: howletcute/todo-app:latest # Or change tag to chat-app if you prefer
    container_name: chat_web_app # Renamed container
    ports:
      - "5001:5000" # Keep host port 5001 mapped to container 5000
    environment:
      # Point to the redis service named 'db' below
      - REDIS_HOST=db
      - REDIS_PORT=6379
      # Set a secret key for Flask session management (use Docker secrets in prod)
      - SECRET_KEY=compose_secret_key_!@#_needs_changing_in_prod
      - PYTHONUNBUFFERED=1
    depends_on:
      - db # Simple dependency is enough for Redis
    restart: unless-stopped

  db: # Renamed service to 'db', but using Redis image
    image: redis:7-alpine # Use official Redis alpine image
    container_name: chat_redis_db # Renamed container
    expose: # Only expose port internally, no need to map to host usually
      - "6379"
    volumes:
      - redis_data:/data # Persist redis data
    restart: unless-stopped

volumes:
  redis_data: # Define volume for redis