apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # Passwords MUST be base64 encoded.
  # Generate using: echo -n 'your-very-strong-password' | base64
  POSTGRES_PASSWORD: Rk9CY1RkdFVnb3IwVE9lRkEya1ZrTFE5YjgxR3pQZlg=
  POSTGRES_USER: dXNlcg== #