# k8s/postgres-deployment.yaml
apiVersion: apps/v1
kind: Deployment # Using Deployment for simplicity (1 replica)
metadata:
  name: postgres-deployment
  labels:
    app: postgres # Label for service selector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14-alpine # Use official Postgres image
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-creds # Name of the K8s Secret object
          env:
            - name: POSTGRES_DB
              value: "chat_db"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - mountPath: /var/lib/postgresql/data # Mount the persistent volume here
              name: postgres-storage
          # Define basic resource requests/limits
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m" # 0.1 CPU
            limits:
              memory: "512Mi"
              cpu: "250m"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc # Use the PVC created earlier
