apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: chat-web
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: chat-web
  template:
    metadata:
      labels:
        app: chat-web
    spec:
      containers:
        - name: web
          image: howletcute/chat-app:latest 
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: postgres-creds
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: SECRET_KEY 
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret 
                  key: POSTGRES_USER 
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_HOST
              value: "postgres-svc" 
            - name: DB_NAME
              value: "chat_db" 
            - name: DATABASE_URL 
              value: "" 
            - name: REDIS_HOST
              value: "redis-service" 
            - name: REDIS_PORT
              value: "6379"
            - name: PYTHONUNBUFFERED 
              value: "1"
            - name: FLASK_CONFIG
              value: "prod"
            - name: SENDGRID_API_KEY
              valueFrom:
                  secretKeyRef:
                    name: sendgrid-secret  
                    key: SENDGRID_API_KEY  
            - name: MAIL_DEFAULT_SENDER
              value: "noreply@howlet.site" 

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m" 
            limits:
              memory: "256Mi"
              cpu: "250m"
