# k8s/web-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: chat-web
spec:
  replicas: 1 # Start with one replica
  selector:
    matchLabels:
      app: chat-web
  template:
    metadata:
      labels:
        app: chat-web
    spec:
      containers:
      - name: web
        image: howletcute/chat-app:latest # Your image from Docker Hub
        ports:
        - containerPort: 5000 # The port gunicorn listens on
        env:
          # Environment variables for the application
          - name: REDIS_HOST
            value: "redis-service" # Connect to the Redis K8s Service name
          - name: REDIS_PORT
            value: "6379"
          - name: SECRET_KEY
            # In production use K8s Secrets: kubectl create secret generic flask-secret --from-literal=secret-key='YOUR_REAL_SECRET'
            value: "a_secret_key_for_k8s_deployment_!@#" # Replace with a real secret later
          - name: PYTHONUNBUFFERED # Already set in Dockerfile, but can be explicit
            value: "1"
        # Add basic resource requests/limits
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m" # 0.1 CPU
          limits:
            memory: "256Mi"
            cpu: "250m"