# ansible/configure-vm.yml
---
- name: Configure VM and Install Docker
  hosts: gcp_vms # Target hosts defined in inventory.ini
  become: yes # Execute tasks with sudo (root privileges)
  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600 # Update only if cache is older than 1 hour

    - name: Install prerequisite packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Create directory for Docker GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker official GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.gpg
        mode: '0644'
        force: yes # Overwrite if exists, ensures latest key

    - name: Add Docker apt repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        filename: docker # Creates /etc/apt/sources.list.d/docker.list

    - name: Update apt cache again after adding new repo
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker Engine, CLI, Containerd, and Compose plugin
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin # Installs 'docker compose' (v2)
        state: present

    - name: Ensure Docker service is running and enabled on boot
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Add remote user (ansible_user) to the docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}" # Use the user defined in inventory vars
        groups: docker
        append: yes # Add to existing groups, don't replace
      notify: Restart SSH # See handlers below

  handlers: # Handlers run only if notified by a task (change occurred)
    - name: Restart SSH
      ansible.builtin.service:
         name: sshd # Or 'ssh' depending on the OS
         state: restarted
      listen: "Restart SSH"
      # Note: Adding user to group often requires logout/login or ssh restart to take effect.
      # Restarting sshd might briefly disconnect Ansible, but usually recovers.
      # A more robust way might involve rebooting or specific session management.