# .github/workflows/deploy.yml
name: Build and Deploy Chat App # Renamed workflow

on:
  push:
    branches: [ main ] # Or 'master'

jobs:
  build-and-push: 
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chat-app:latest # Use new image name

  deploy:
    name: Deploy to GCP VM using Ansible
    runs-on: ubuntu-latest
    needs: build-and-push # Depends on the build job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Need checkout to access ansible files

      - name: Set up Python for Ansible
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install ansible # Or ansible-core

      - name: Configure SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH host key to known_hosts
        # Important: Ensures the runner trusts the host key of your VM
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # Create a temporary inventory file for Ansible
      - name: Create Ansible Inventory File
        run: |
          echo "[gcp_vms]" > temp_inventory.ini
          echo "${{ secrets.SSH_HOST }}" >> temp_inventory.ini
          echo "[gcp_vms:vars]" >> temp_inventory.ini
          echo "ansible_user=${{ secrets.SSH_USER }}" >> temp_inventory.ini
          echo "ansible_python_interpreter=/usr/bin/python3" >> temp_inventory.ini

      - name: Run Ansible Deployment Playbook
        run: ansible-playbook -i temp_inventory.ini ansible/deploy-app.yml